# -*- coding: utf-8 -*-
"""MeugameImparouPar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CHFCwOxx9ZWCVHQlH_mzjBNmry1Kpct
"""

Jogador1 = input("-> Digite o nome do primeiro jogador: ")
Jogador2 = input("-> Digite o nome do segundo jogador: ")

print(f"// Quem escolhe primeiro, {Jogador1} ou {Jogador2}?")
primeiro_jogador = input(f"-> Digite 1 para escolher {Jogador1} ou 2 para escolher {Jogador2}! ")
segundo_jogador = None

if primeiro_jogador == "1":
  primeiro_jogador = Jogador1
  segundo_jogador = Jogador2
elif primeiro_jogador == "2":
    primeiro_jogador = Jogador2
    segundo_jogador = Jogador1

print(f"Então: {primeiro_jogador} e {segundo_jogador}!")

print("// Digite 0 para escolher PAR e 1 para ÍMPAR")
escolha = input(f"-> {primeiro_jogador}, você quer par ou ímpar? ")
escolha2 = None

if escolha == "ímpar" or escolha == "impar" or escolha == "1":
  escolha = "ÍMPAR"
  escolha2 = "PAR"
elif escolha == "par" or escolha == "0":
  escolha = "PAR"
  escolha2 = "ÍMPAR"

print(f"// {segundo_jogador} você ficou com {escolha2} e o {primeiro_jogador} escolheu {escolha}.")

numero1 = int(input(f"-> {primeiro_jogador} escolha um número: "))
numero2 = int(input(f"-> {segundo_jogador} escolha um número: "))

soma = numero1 + numero2

if soma % 2 == 0:
  vencedor = "PAR"
else:
  vencedor = "ÍMPAR"

if vencedor == escolha:
 print(f"// {primeiro_jogador} venceu!!!")
else:
  print(f"// {segundo_jogador} venceu!!")